FROM ubi8/ubi:8.3

ENV NEXUS_VERSION=2.14.3-02 \
    NEXUS_HOME=/opt/nexus

RUN yum install -y java-1.8.0-openjdk-devel && yum clean all && \
    groupadd -r nexus -f -g 1001 && \
    useradd -u 1001 -g nexus -s /bin/nologin -r -m -d ${NEXUS_HOME} nexus && \
    chown nexus:nexus -R ${NEXUS_HOME} && \
    chmod -R 755 ${NEXUS_HOME}

USER nexus

ADD ./nexus-2.14.3-02-bundle.tar.gz ${NEXUS_HOME}/
ADD ./nexus-start.sh ${NEXUS_HOME}/

RUN ln -s ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2


WORKDIR ${NEXUS_HOME}

VOLUME ${NEXUS_HOME}/sonatype-work

CMD ["/bin/sh", "nexus-start.sh"]

